name: 'Handlebars Template Render Action'
description: 'Renders Handlebars templates with JSON data'
inputs:
  template-path:
    description: 'Path to the Handlebars template file'
    required: true
  data:
    description: 'JSON data to apply to the template'
    required: false
    default: '{}'
  data-path:
    description: 'Path to json data file'
    required: false
    default: ''
outputs:
  rendered-template:
    description: 'Rendered Handlebars template'
runs:
  using: 'node16'
  main: 'dist/index.js'
